extends:
  - google
  - plugin:react/recommended

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true

env:
  browser: true
  es6: true
  node: true

rules:
  arrow-parens: [error, as-needed]
  brace-style: [error, 1tbs, allowSingleLine: true]
  block-spacing: [error, always]
  max-len: off
  new-cap:
    - error
    - capIsNewExceptions:
      - Map
  no-console: warn
  object-curly-spacing: [error, always]
  padded-blocks: off
  require-jsdoc: off
